# Generated by Django 4.2.3 on 2023-07-24 21:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventpolls", "0003_alter_event_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscriptions",
            new_name="Subscription",
        ),
    ]
